const checkedAt = '2026-09-16';
const trial = (data) => ({kind:'Randomized trial',level:'Human',journal:'New England Journal of Medicine',reviewScope:'Published abstract and bibliographic record',checkedAt,trialIds:[],goals:[],...data});
const official = (data) => ({kind:'Official document',level:'Regulatory',year:2026,checkedAt,reviewScope:'Relevant official document sections',populationGroup:'Indication-specific',population:null,sampleSize:null,dose:null,duration:null,comparator:null,adverseEvents:null,goals:[],...data});

export const TIRZEPATIDE = {
  id:'tirzepatide',name:'Tirzepatide',aliases:'Mounjaro · Zepbound · LY3298176',category:'Prescription medicine',checkedAt,
  status:'Partially documented',
  introduction:'A dual GIP/GLP-1 receptor agonist studied for weight management, blood glucose control and other metabolic outcomes. Benefits depend on the population, dose and outcome being studied.',
  takeaway:'Substantial weight loss in obesity trials, with gastrointestinal side effects and prescription-specific precautions. Long-term treatment and stopping treatment are different research questions.',
  scope:'A targeted selection of five clinical trial publications and three official documents. This is not an exhaustive literature review or an independent clinical sign-off. Other indications and newer secondary analyses are not fully covered.',
  sources:[
    trial({id:'surmount1',label:'SURMOUNT-1',title:'Tirzepatide Once Weekly for the Treatment of Obesity',authors:'Jastreboff et al.',year:2022,pmid:'35658024',doi:'10.1056/NEJMoa2206038',url:'https://pubmed.ncbi.nlm.nih.gov/35658024/',trialIds:['NCT04184622'],goals:['Weight'],populationGroup:'Adults without diabetes',population:'Adults with BMI ≥30, or ≥27 with a weight-related complication; diabetes excluded.',sampleSize:2539,dose:'5, 10 or 15 mg tirzepatide, subcutaneous weekly, following escalation.',duration:'72 weeks',comparator:'Placebo; lifestyle support in all groups',design:'Phase 3, double-blind randomized trial',result:'Average weight change at week 72: −15.0%, −19.5% and −20.9% by dose, versus −3.1% with placebo.',adverseEvents:'Mostly gastrointestinal events; adverse-event discontinuations: 4.3–7.1% across active arms versus 2.6% with placebo.',limitations:'Manufacturer-funded. Excludes diabetes. These are treatment-regimen estimates, not the separate on-treatment estimand. No direct semaglutide comparison.',reviewScope:'PubMed abstract and publisher results/methods excerpts'}),
    trial({id:'surmount5',label:'SURMOUNT-5',title:'Tirzepatide as Compared with Semaglutide for the Treatment of Obesity',authors:'Aronne et al.',year:2025,pmid:'40353578',doi:'10.1056/NEJMoa2416394',url:'https://pubmed.ncbi.nlm.nih.gov/40353578/',trialIds:['NCT05822830'],goals:['Weight','Comparison'],populationGroup:'Adults without diabetes',population:'Adults with obesity without type 2 diabetes.',sampleSize:751,dose:'Tirzepatide 10/15 mg or semaglutide 1.7/2.4 mg, maximum tolerated, subcutaneous weekly.',duration:'72 weeks',comparator:'Semaglutide (active comparator)',design:'Phase 3b, open-label randomized trial',result:'Weight change: −20.2% with tirzepatide (95% CI −21.4 to −19.1), versus −13.7% with semaglutide (−14.9 to −12.6).',adverseEvents:'Gastrointestinal events predominated, usually mild/moderate and during escalation.',limitations:'Open-label and manufacturer-funded. Findings apply to the studied obesity doses and population, not every use or dose of either medicine.'}),
    trial({id:'surpass2',label:'SURPASS-2',title:'Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes',authors:'Frías et al.',year:2021,pmid:'34170647',doi:'10.1056/NEJMoa2107519',url:'https://pubmed.ncbi.nlm.nih.gov/34170647/',trialIds:['NCT03987919'],goals:['Blood glucose','Comparison'],populationGroup:'Adults with type 2 diabetes',population:'Adults with type 2 diabetes.',sampleSize:1879,dose:'Tirzepatide 5/10/15 mg versus semaglutide 1 mg, subcutaneous weekly.',duration:'40 weeks',comparator:'Semaglutide 1 mg weekly',design:'Phase 3, open-label randomized trial',result:'HbA1c changes: −2.01, −2.24 and −2.30 percentage points with tirzepatide, versus −1.86 with semaglutide.',adverseEvents:'Nausea, diarrhea and vomiting common. Serious adverse events: 5–7% with tirzepatide versus 3% with semaglutide.',limitations:'Manufacturer-funded, open-label. Comparator was 1 mg, not the 2.4 mg obesity dose. HbA1c is not a cardiovascular event outcome.'}),
    trial({id:'cvot',label:'SURPASS-CVOT',title:'Cardiovascular Outcomes with Tirzepatide versus Dulaglutide in Type 2 Diabetes',authors:'Nicholls et al.',year:2025,pmid:'41406444',doi:'10.1056/NEJMoa2505928',url:'https://pubmed.ncbi.nlm.nih.gov/41406444/',trialIds:['NCT04255433'],goals:['Cardiovascular'],populationGroup:'Adults with diabetes and cardiovascular disease',population:'Type 2 diabetes with established atherosclerotic cardiovascular disease.',sampleSize:13299,dose:'Tirzepatide up to 15 mg versus dulaglutide 1.5 mg, subcutaneous weekly.',duration:null,comparator:'Dulaglutide 1.5 mg weekly',design:'Double-blind randomized noninferiority trial',result:'Cardiovascular death, infarction or stroke: 12.2% versus 13.1%; hazard ratio 0.92 (95.3% CI 0.83–1.01). Noninferiority met; superiority not established (P=0.09).',adverseEvents:'Similar overall incidence; more gastrointestinal events with tirzepatide.',limitations:'Manufacturer-funded. 13,165 in modified intention-to-treat analysis after 134 exclusions. Follow-up duration not extracted from the reviewed abstract. No placebo arm.'}),
    trial({id:'surmount4',label:'SURMOUNT-4',title:'Continued Treatment With Tirzepatide for Maintenance of Weight Reduction in Adults With Obesity: The SURMOUNT-4 Randomized Clinical Trial',authors:'Aronne et al.',journal:'JAMA',year:2024,onlineYear:2023,pmid:'38078870',doi:'10.1001/jama.2023.24945',url:'https://pubmed.ncbi.nlm.nih.gov/38078870/',trialIds:['NCT04660643'],goals:['Weight maintenance'],populationGroup:'Adults without diabetes',population:'Adults with obesity/overweight and complications, without diabetes; randomized after a tirzepatide lead-in.',sampleSize:670,dose:'Maximum tolerated 10 or 15 mg subcutaneous weekly.',duration:'36-week lead-in, then 52 weeks randomized follow-up',comparator:'Switch to placebo after initial tirzepatide treatment',design:'Phase 3, double-blind randomized withdrawal trial',result:'From week 36 to 88: another 5.5% weight reduction with continued treatment, versus 14.0% regain after switching to placebo.',adverseEvents:'Mostly mild/moderate gastrointestinal events, more frequent with continued tirzepatide.',limitations:'783 entered lead-in; only 670 were randomized. Results apply to lead-in completers, not everyone starting treatment. Manufacturer-funded. Print year 2024, online 2023.'}),
    official({id:'label',label:'US prescribing information',title:'Zepbound US prescribing information, revised August 2026',authors:'Eli Lilly, FDA-approved prescribing information',journal:'US prescribing information',url:'https://pi.lilly.com/us/zepbound-uspi.pdf',goals:['Safety','Doses','Mechanism','Regulation'],result:'US indications include chronic weight management and moderate-to-severe obstructive sleep apnea in adults with obesity.',limitations:'US product-specific information. Not a primary trial; not evidence of approval for every researched outcome.'}),
    official({id:'ema',label:'EMA overview',title:'Mounjaro: European public assessment report',authors:'European Medicines Agency',journal:'EMA',url:'https://www.ema.europa.eu/en/medicines/human/EPAR/mounjaro',goals:['Regulation'],result:'EU authorization covers type 2 diabetes from age 10 and adult weight management within the specified eligibility criteria; prescription required.',limitations:'EU jurisdiction. The adult trial data shown here do not establish pediatric effects. Consult current product information for eligibility.'}),
    official({id:'fda-update',label:'FDA safety update',title:'FDA requests removal of suicidal behavior and ideation warning from GLP-1 RA medications',authors:'US Food and Drug Administration',journal:'FDA Drug Safety Communication',url:'https://www.fda.gov/drugs/drug-safety-communications/fda-requests-removal-suicidal-behavior-and-ideation-warning-glucagon-peptide-1-receptor-agonist-glp',goals:['Safety'],result:'The January 2026 FDA review found no increased risk of suicidal ideation/behavior and requested removal of this warning, including for Zepbound.',limitations:'Regulatory evidence review, not a claim that all psychiatric risks or individual symptoms are excluded.'}),
  ],
  outcomes:[
    {id:'weight',label:'Weight management',status:'supported',confidence:'Consistent trial evidence',reason:'Placebo-controlled and direct comparator trials support weight reduction in the studied adult populations.',summary:'Weight reduction is supported in adults with obesity without diabetes. The magnitude depends on dose, comparator and analysis.',sourceIds:['surmount1','surmount5']},
    {id:'glucose',label:'Blood glucose',status:'supported',confidence:'Supported in type 2 diabetes',reason:'A large randomized trial measured HbA1c directly; this pilot has not synthesized the whole diabetes program.',summary:'HbA1c fell more than with semaglutide 1 mg in SURPASS-2. Do not transfer this comparison to obesity-dose semaglutide.',sourceIds:['surpass2']},
    {id:'cardio',label:'Cardiovascular events',status:'supported',confidence:'Noninferiority demonstrated',reason:'A large active-comparator trial supports noninferiority; its superiority test was not significant.',summary:'SURPASS-CVOT is published. It does not establish fewer major cardiovascular events than dulaglutide.',sourceIds:['cvot']},
    {id:'maintenance',label:'After stopping treatment',status:'supported',confidence:'Withdrawal trial evidence',reason:'Randomized withdrawal supports a maintenance effect in people who completed the initial treatment period.',summary:'Weight regain after withdrawal is a material limitation when interpreting short-term weight loss.',sourceIds:['surmount4']},
  ],
  risks:[
    {label:'Common gastrointestinal effects',text:'Nausea, diarrhea, vomiting and constipation occur in human studies.',sourceIds:['label','surmount1','surpass2']},
    {label:'Contraindications',text:'US label: personal/family medullary thyroid carcinoma, MEN 2 or serious hypersensitivity.',sourceIds:['label']},
    {label:'Animal signal, uncertain human relevance',text:'Thyroid C-cell tumors occurred in rats. Human causation is unknown; this is not a measured “rare human side effect”.',sourceIds:['label']},
    {label:'Clinician review',text:'Pancreatitis, gallbladder disease, dehydration-related kidney injury, severe gastroparesis, retinopathy and planned anesthesia need consideration. Pregnancy requires prescriber review.',sourceIds:['label']},
    {label:'Interactions',text:'Insulin/sulfonylureas increase hypoglycemia risk. Delayed gastric emptying can affect oral drugs. The label specifies additional/non-oral contraception for four weeks after initiation and each escalation. Combining with another GLP-1 agonist is not recommended.',sourceIds:['label']},
    {label:'Updated warning',text:'Older suicidal-ideation warnings should be interpreted alongside the FDA’s 2026 review.',sourceIds:['fda-update']},
  ],
  mechanisms:[
    {label:'GIP + GLP-1 receptors',text:'Tirzepatide activates both receptors.',evidence:'Label pharmacology',sourceIds:['label']},
    {label:'Appetite and glucose',text:'Reduced calorie intake, glucose-dependent insulin secretion and reduced glucagon contribute to its effects.',evidence:'Human pharmacodynamic findings',sourceIds:['label']},
    {label:'Brain pathways',text:'Specific neuronal distribution and activation findings described in the label come from animals.',evidence:'Preclinical findings',sourceIds:['label']},
  ],
  regulation:[{label:'United States',text:'Zepbound: weight management and obstructive sleep apnea within the approved adult indications.',sourceIds:['label']},{label:'European Union',text:'Mounjaro: type 2 diabetes and adult weight management under the eligibility criteria in the current product information.',sourceIds:['ema']}],
  charts:[
    {id:'placebo',sourceId:'surmount1',title:'Weight change versus placebo',population:'2,539 adults without diabetes',duration:'72 weeks',unit:'% body weight change',note:'Treatment-regimen estimand. Negative values indicate weight reduction. End-point estimates with 95% confidence intervals; not a time course.',arms:[{name:'Tirzepatide 5 mg',value:-15,ci:[-15.9,-14.2]},{name:'Tirzepatide 10 mg',value:-19.5,ci:[-20.4,-18.5]},{name:'Tirzepatide 15 mg',value:-20.9,ci:[-21.8,-19.9]},{name:'Placebo',value:-3.1,ci:[-4.3,-1.9]}]},
    {id:'head-to-head',sourceId:'surmount5',title:'Tirzepatide versus semaglutide',population:'751 adults with obesity without diabetes',duration:'72 weeks',unit:'% body weight change',note:'Direct randomized comparison at maximum tolerated doses. Groups were not blinded. End-point estimates with 95% confidence intervals.',arms:[{name:'Tirzepatide 10/15 mg',value:-20.2,ci:[-21.4,-19.1]},{name:'Semaglutide 1.7/2.4 mg',value:-13.7,ci:[-14.9,-12.6]}]},
  ],
};

// Contrast fixtures are deliberately partial records, not silently completed profiles.
export const CREATINE = {
  id:'creatine-monohydrate',name:'Creatine monohydrate',category:'Supplement',aliases:'Creatine',checkedAt,status:'Partially documented',
  introduction:'A contrast profile for evidence drawn from a systematic review.',takeaway:'A reviewed meta-analysis supports additional lean mass with resistance training. This pilot does not cover all uses, doses or safety questions.',scope:'One review publication has been checked. Its 12 included studies are not 12 independently reviewed trial records in this library.',
  sources:[{id:'creatine-review',label:'Body composition review',title:'The Effect of Creatine Supplementation on Resistance Training-Based Changes to Body Composition: A Systematic Review and Meta-analysis',authors:'Desai et al.',year:2024,pmid:'39074168',doi:'10.1519/JSC.0000000000004862',url:'https://pubmed.ncbi.nlm.nih.gov/39074168/',journal:'Journal of Strength and Conditioning Research',kind:'Systematic review',level:'Human',populationGroup:'Adults under 50',population:'Adults younger than 50 undertaking resistance training.',sampleSize:null,dose:null,duration:null,comparator:'Resistance training without creatine',goals:['Body composition'],result:'The review of 12 studies estimated 1.14 kg greater lean body mass (95% CI 0.69–1.59). Lean mass is not a direct measure of muscle tissue alone.',adverseEvents:null,limitations:'Dose, duration, total unique participants and safety details were not extracted from the abstract. Evidence is specific to resistance training; risk of bias varied.',reviewScope:'PubMed abstract and bibliographic record',checkedAt}],
  outcomes:[{id:'lean-mass',label:'Lean body mass with training',status:'supported',confidence:'Review-level support',reason:'A pooled estimate supports an average benefit; a complete risk-of-bias appraisal is not included.',summary:'Additional lean mass was observed on average. This does not establish an equivalent benefit for every population or formulation.',sourceIds:['creatine-review']}],risks:[],mechanisms:[],regulation:[],charts:[],
};
export const FADOGIA = {
  id:'fadogia-agrestis',name:'Fadogia agrestis',category:'Botanical',aliases:'Fadogia',checkedAt,status:'Partially documented',
  introduction:'A contrast profile showing why animal findings cannot establish human benefits or safe doses.',takeaway:'No verified human conclusion found in the sources reviewed.',scope:'One animal publication examined, plus the existing audit as a discovery lead. No exhaustive human literature search is claimed.',
  sources:[{id:'fadogia-rats',label:'Rat testicular-function study',title:'Effects of oral administration of aqueous extract of Fadogia agrestis stem on some testicular function indices of male rats',authors:'Yakubu et al.',year:2008,onlineYear:2007,pmid:'18023305',doi:'10.1016/j.jep.2007.10.004',url:'https://pubmed.ncbi.nlm.nih.gov/18023305/',journal:'Journal of Ethnopharmacology',kind:'Animal study',level:'Animal',populationGroup:'Male rats',population:'Male rats, four experimental groups.',sampleSize:null,dose:'18, 50 or 100 mg/kg aqueous stem extract orally daily (rats only).',duration:'28 days; recovery assessed for 10 days',comparator:'Distilled water',goals:['Safety'],result:'Changes in testicular biochemical indices were interpreted by the authors as adverse effects on rat testicular function.',adverseEvents:'Testicular-function signals in rats; human incidence unknown.',limitations:'Animal study, small-study details incomplete in abstract; no human dose or benefit can be inferred. Print year 2008, online 2007.',reviewScope:'PubMed abstract and bibliographic record',checkedAt}],
  outcomes:[{id:'human',label:'Human benefit',status:'not_found',confidence:'Not evaluated in humans here',reason:'The reviewed source is an animal study. A missing human record is not proof of no effect.',summary:'Human efficacy and safe dosing are not established by this reviewed source.',sourceIds:['fadogia-rats']}],
  risks:[{label:'Preclinical safety signal',text:'The rat study raises safety questions; it cannot quantify human risk.',sourceIds:['fadogia-rats']}],mechanisms:[],regulation:[],charts:[],
};
export const RESEARCH_PROFILES = Object.freeze(Object.fromEntries([TIRZEPATIDE,CREATINE,FADOGIA].map(p=>[p.id,p])));
