// Generated from the final catalogue audit export.
export const BATCH4_AUDIT_CHUNK_9 = [
  {
    "recordNumber": 391,
    "batchNumber": 4,
    "catalogId": "moringa",
    "inputName": "Moringa Oleifera",
    "canonicalName": "Moringa oleifera leaf powder [657, 658, 659]",
    "aliases": "Moringa oleifera; Moringa oleifera Lam.; Moringa leaf powder [657, 658, 659]",
    "category": "Botanical dietary supplement / plant-derived leaf powder [657, 658, 659]",
    "latestVerifiedPublicationYear": 2026,
    "humanStudyCount": 2,
    "totalStudyCount": 3,
    "evidenceByGoal": "Metabolic outcomes in adults with diabetes: a pilot clinical study enrolled 44 diabetic patients from Adrar city. The source reports 3,600 mg of Moringa oleifera leaf powder twice daily, at breakfast and 7 p.m., for 90 consecutive days, alongside regular hypoglycemic medications; outcomes were assessed on days 0, 3, 7, 30, and 90. [657] The study evaluated serum lipids, blood sugar, HbA1c, weight, BMI, and blood pressure. [657] It reported statistically significant effects on blood sugar/HbA1c, LDL-C, and HDL-C, with LDL-C and HbA1c reduced and HDL-C elevated; weight, BMI, and blood pressure were not significantly affected. [657] No side effect was reported. [657] Comparator and randomization were not verified in the reviewed source. The key limitation was its preliminary pilot nature; the source states that a more extensive trial is needed to determine the optimal dose and long-term advantages. [657]\n\nModerate acute malnutrition in children: a randomized double-blind clinical trial enrolled 400 children aged 6–59 months with moderate acute malnutrition at outpatient nutritional recovery centers. The intervention was Moringa oleifera dry leaf powder plus ready-to-use supplementary foods (RUSF), compared with RUSF plus placebo. [657] The source does not report the dose or exact supplementation duration; these fields are not verified in the reviewed source. There was no difference in average weight gain, mid-upper-arm circumference, or height. Median length of stay was 5 weeks with Moringa and 4 weeks with placebo, with no statistically significant difference (P=0.522); the cure rate was 82% in the Moringa group, with RR 1.03 (0.94 to 1.13). Renal and hepatic toxicity was not observed. The key limitation reported by the source is that supplementation in children already receiving dietary treatment, with the dose reduced to a minimum and the supplementation duration, may have contributed to the absence of effect.",
    "efficacyScore": 2,
    "evidenceQualityScore": 2,
    "safetySummary": "In the diabetes pilot, no side effect was reported by any participant. [657] In the pediatric malnutrition trial, renal and hepatic toxicity was not observed. These findings are limited to the reported trial observations and do not establish broader safety across formulations, doses, durations, or populations.",
    "knownInteractions": "Not verified in reviewed sources. [657, 658, 659]",
    "regulatoryStatus": "Not verified in reviewed sources. [657, 658, 659]",
    "limitations": "Three candidate records were reviewed, but the 2026 record is a narrative review rather than a uniquely identifiable primary human outcome study and was not counted. The eligible evidence consists of two different clinical contexts: a preliminary 90-day diabetes pilot and a pediatric malnutrition trial with no significant nutritional-recovery benefit. The first source does not verify a comparator or randomization details; the second does not report an exact dose or supplementation duration in the reviewed source. Findings should not be transferred to other Moringa formulations or analogs. [657] [657] [657] [657] [657] [657]",
    "missingFields": "For the diabetes pilot, comparator and randomization details were not verified in the reviewed source. For the pediatric malnutrition trial, exact dose and supplementation duration were not verified in the reviewed source. Long-term clinical benefits were not verified in the reviewed sources. [657] [657] [657] [657] [657] [657]",
    "editorialReviewRequired": true,
    "sources": [
      {
        "pmid": null,
        "doi": null,
        "title": "Study of the effect of Moringa oleifera leaves powder in Southwestern Algerian diabetic patients: a pilot clinical trial",
        "year": 2023,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.notulaebiologicae.ro/index.php/nsb/article/download/11554/9599"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Effect of Moringa supplementation in the management of moderate malnutrition in children under 5 receiving ready-to-use supplementary foods in Niger: A randomized clinical trial",
        "year": 2021,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://gsconlinepress.com/journals/gscarr/sites/default/files/GSCARR-2021-0189.pdf"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Moringa oleifera Lamk. as a Promising Adjunct Therapeutic Candidate: A Narrative Review of Human Studies and Published Case Reports",
        "year": 2026,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.dovepress.com/article/download/111834"
      }
    ]
  },
  {
    "recordNumber": 392,
    "batchNumber": 4,
    "catalogId": "hordenine",
    "inputName": "Hordenine",
    "canonicalName": "Hordenine [660, 661, 662]",
    "aliases": "Hordinine (spelling variant appearing in one reviewed record) [660, 661, 662]",
    "category": "Not verified in reviewed sources. [660, 661, 662]",
    "latestVerifiedPublicationYear": null,
    "humanStudyCount": 0,
    "totalStudyCount": 3,
    "evidenceByGoal": "No verified human conclusion found in the sources reviewed. [660, 661, 662]",
    "efficacyScore": 0,
    "evidenceQualityScore": 0,
    "safetySummary": "No safety conclusion was verified from an eligible primary human hordenine study. The reviewed hordenine record reports rapid heart rates and high blood pressure as side effects. [660, 661, 662]",
    "knownInteractions": "Not mentioned in source. [660, 661, 662]",
    "regulatoryStatus": "The reviewed hordenine record reports that hordenine is an unapproved dietary ingredient and that an NDI notification had not been submitted. [660, 661, 662]",
    "limitations": "All three supplied candidate records were reviewed. The 2013 and 2015 human studies concern higenamine, not hordenine, so their evidence was excluded as an identity mismatch. The 2023 hordenine record was not verified as an eligible primary human outcome study. Dose, duration, comparator, outcomes, adverse events, and limitations from the higenamine studies were therefore not transferred to hordenine. [660, 661, 662]",
    "missingFields": "No eligible hordenine primary human outcome study was verified; consequently, clinically studied goal details and hordenine-specific dose, duration, comparator, outcomes, adverse events, and key limitations are unavailable from eligible records. [660, 661, 662]",
    "editorialReviewRequired": true,
    "sources": [
      {
        "pmid": null,
        "doi": null,
        "title": "Clinical safety assessment of oral higenamine supplementation in healthy, young men",
        "year": 2015,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.semanticscholar.org/paper/704ec8120e9d5605745bf49af2c50fc1b179afba"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Hordenine - Unapproved Dietary Ingredient",
        "year": 2023,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.semanticscholar.org/paper/c42d9ef87b191db0ecc865278d07c7d262b64bf1"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Acute oral intake of a higenamine-based dietary supplement increases circulating free fatty acids and energy expenditure in human subjects",
        "year": 2013,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://lipidworld.biomedcentral.com/counter/pdf/10.1186/1476-511X-12-148"
      }
    ]
  },
  {
    "recordNumber": 393,
    "batchNumber": 4,
    "catalogId": "dihydromyricetin",
    "inputName": "Dihydromyricetin (DHM)",
    "canonicalName": "Dihydromyricetin (DHM) [663, 664, 665]",
    "aliases": "DHM; Dihydromyricetin [663, 664, 665]",
    "category": "Plant-derived flavonoid / bioactive flavonoid [663, 664, 665]",
    "latestVerifiedPublicationYear": null,
    "humanStudyCount": 0,
    "totalStudyCount": 3,
    "evidenceByGoal": "No verified human conclusion found in the sources reviewed. [663, 664, 665]",
    "efficacyScore": 0,
    "evidenceQualityScore": 0,
    "safetySummary": "Not verified in reviewed sources. [663, 664, 665]",
    "knownInteractions": "The source reports that combining DHM with turmeric, daidzein, or resveratrol diminished DHM effects; clinical interactions were not verified in reviewed sources. [665]",
    "regulatoryStatus": "Not verified in reviewed sources. [663, 664, 665]",
    "limitations": "Only the three supplied records were assessed. Record 1 describes experiments in C57BL/6J mice; record 2 is a systematic review whose two clinical studies used Hovenia dulcis extracts and did not directly evaluate isolated DHM; record 3 describes experiments in rats. Therefore, no human design, population, sample size, dose, duration, comparator, outcome, or adverse-event profile for isolated DHM was eligible for extraction. [663, 664, 665]",
    "missingFields": "For eligible primary human studies: design, population, sample size, dose, duration, comparator, outcome, adverse events, and key limitation are not verified in reviewed sources because no eligible primary human study passed the audit. [663, 664, 665]",
    "editorialReviewRequired": true,
    "sources": [
      {
        "pmid": null,
        "doi": null,
        "title": "Identification of Dihydromyricetin and Metabolites in Serum and Brain Associated with Acute Anti-Ethanol Intoxicating Effects in Mice",
        "year": 2021,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.mdpi.com/1422-0067/22/14/7460/pdf?version=1626092003"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Therapeutic Effects of Dihydromyricetin on Wholly Alcohol-Attributed Conditions: A Systematic Review",
        "year": 2026,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://doi.org/10.3390/nu18142221"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Antialcohol Effects of Dihydromyricetin in Combination With Other Flavonoids",
        "year": 2020,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://doi.org/10.1177/1934578x20946250"
      }
    ]
  },
  {
    "recordNumber": 394,
    "batchNumber": 4,
    "catalogId": "calcium-d-glucarate",
    "inputName": "Calcium D-Glucarate",
    "canonicalName": "Calcium D-Glucarate [666, 667, 668]",
    "aliases": "Calcium-D-glucarate; calcium glucarate [666, 667, 668]",
    "category": "Dietary supplement / calcium salt of D-glucaric acid [666, 667, 668]",
    "latestVerifiedPublicationYear": null,
    "humanStudyCount": 0,
    "totalStudyCount": 3,
    "evidenceByGoal": "No verified human conclusion found in the sources reviewed. [666, 667, 668]",
    "efficacyScore": 0,
    "evidenceQualityScore": 0,
    "safetySummary": "Not verified in reviewed sources. [666, 667, 668]",
    "knownInteractions": "Not verified in reviewed sources. [666, 667, 668]",
    "regulatoryStatus": "Not verified in reviewed sources. [666, 667, 668]",
    "limitations": "Exactly three candidate records were reviewed. Record 1 studied calcium carbonate plus vitamin D3, not calcium D-glucarate; record 2 is a metabolism-focused record and does not report an eligible primary human outcome study; record 3 concerns calcium and vitamin D intake and is not an exact-ingredient calcium D-glucarate study. Reviews, non-primary records, identity mismatches, and unverified/inaccessible records contribute zero eligible human studies. Clinical design, population, sample size, dose, duration, comparator, outcomes, adverse events, and key limitations for an eligible exact-ingredient human study are therefore not available. [666, 667, 668]",
    "missingFields": "No eligible exact-ingredient primary human outcome study was identified; consequently, study-level clinical fields are not applicable. [666, 667, 668]",
    "editorialReviewRequired": false,
    "sources": [
      {
        "pmid": null,
        "doi": null,
        "title": null,
        "year": 2006,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.semanticscholar.org/paper/82b30c29b1bf97f0d9b3e20666f4d30b21deb783"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Metabolism of Glucaric Acid Calcium D-Glucarate Glucaric acid D-glucaro-6 , 3-lactone * D-glucaro -",
        "year": 2002,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.semanticscholar.org/paper/8c58d42bcea1ec5275d530e31a00944e1a86ac23"
      },
      {
        "pmid": null,
        "doi": null,
        "title": "Calcium and Vitamin D Intake and Risk for Breast Cancer",
        "year": 2007,
        "journal": "not verified",
        "studyDesign": "not verified",
        "population": "not verified",
        "sampleSize": "not verified",
        "doseStudied": "not verified",
        "duration": "not verified",
        "comparator": "not verified",
        "outcomes": "Candidate record reviewed; details only reported in evidence_by_goal.",
        "adverseEvents": "not verified",
        "limitations": "Candidate status assessed at record level.",
        "sourceUrl": "https://www.semanticscholar.org/paper/94bfefe9016c2da9f5200968f6c88efcb62b14d9"
      }
    ]
  }
];

